parameters:
    # Security
    ezsettings.default.security.token_interval_spec: PT1H
    ezsettings.default.user_change_password.templates.form: "@@EzPlatformUser/change_password/index.html.twig"
    ezsettings.default.user_change_password.templates.success: "@@EzPlatformUser/change_password/success.html.twig"
    ezsettings.default.user_forgot_password.templates.form: "@@EzPlatformUser/forgot_password/index.html.twig"
    ezsettings.default.user_forgot_password_success.templates.form: "@@EzPlatformUser/forgot_password/success.html.twig"
    ezsettings.default.user_forgot_password_login.templates.form: "@@EzPlatformUser/forgot_password/with_login.html.twig"
    ezsettings.default.user_forgot_password.templates.mail: "@@EzPlatformUser/forgot_password/mail/forgot_user_password.html.twig"
    ezsettings.default.user_reset_password.templates.form: "@@EzPlatformUser/reset_password/index.html.twig"
    ezsettings.default.user_reset_password.templates.invalid_link: "@@EzPlatformUser/reset_password/invalid_link.html.twig"
    ezsettings.default.user_reset_password.templates.success: "@@EzPlatformUser/reset_password/success.html.twig"

    # Registration
    ezsettings.default.user_registration.group_id: 11
    ezsettings.default.user_registration.templates.form: "@@EzPlatformContentForms/Content/content_edit.html.twig"
    ezsettings.default.user_registration.templates.confirmation: "@@EzPlatformUser/register/register_confirmation.html.twig"

    # User Settings
    ezsettings.default.user_settings_update_view: {}
    ezsettings.default.user_settings_update_view_defaults:
        full:
            default:
                template: "%ezsettings.default.user_settings.templates.update%"
                match: []

    ezsettings.default.user_settings.templates.list: "@@EzPlatformUser/user_settings/list.html.twig"
    ezsettings.default.user_settings.templates.update: "@@EzPlatformUser/user_settings/update.html.twig"

    # User Preferences
    ezsettings.default.user_preferences.short_datetime_format:
        date_format: 'dd/MM/yyyy'
        time_format: 'HH:mm'
    ezsettings.default.user_preferences.full_datetime_format:
        date_format: 'LLLL dd, yyyy'
        time_format: 'HH:mm'
    ezsettings.default.user_preferences.allowed_short_date_formats:
        'mm/dd/yyyy': 'MM/dd/yyyy'
        'mm/dd/yy': 'MM/dd/yy'
        'dd/mm/yyyy': 'dd/MM/yyyy'
        'dd/mm/yy': 'dd/MM/yy'
        'yy/mm/dd': 'yy/MM/dd'
        'mm-dd-yyyy': 'MM-dd-yyyy'
        'mm-dd-yy': 'MM-dd-yy'
        'dd-mm-yyyy': 'dd-MM-yyyy'
        'dd-mm-yy': 'dd-MM-yy'
    ezsettings.default.user_preferences.allowed_short_time_formats:
        'hh:mm AM/PM': 'hh:mm a'
        'hh:mm': 'HH:mm'
    ezsettings.default.user_preferences.allowed_full_date_formats:
        'M dd, yyyy': 'LLLL dd, yyyy'
        'dd M yyyy': 'dd LLLL yyyy'
    ezsettings.default.user_preferences.allowed_full_time_formats:
        'hh:mm AM/PM': 'hh:mm a'
        'hh:mm': 'HH:mm'

    # Additional translations e.g. ['en_US', 'nb_NO']
    ezsettings.default.user_preferences.additional_translations: []

    # Pagination limits
    ezsettings.default.pagination_user.user_settings_limit: 10
