imports:
    - { resource: services/controllers.yaml }
    - { resource: services/validators.yaml }
    - { resource: services/user_settings.yaml }
    - { resource: services/forms.yaml }

parameters:
    ezplatform.user.content_type_identifier: user

services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformUser\EventListener\:
        resource: "../../../lib/EventListener/*"
        public: true
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformUserBundle\Command\:
        resource: "../../Command/*"
        tags:
            - { name: console.command }

    EzSystems\EzPlatformUserBundle\Command\AuditUserDatabaseCommand:
        arguments:
            $connection: '@ezpublish.persistence.connection'

    EzSystems\EzPlatformUser\EventListener\ViewTemplatesListener:
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformUser\ConfigResolver\ConfigurableRegistrationGroupLoader: ~

    EzSystems\EzPlatformUser\ConfigResolver\ConfigurableRegistrationContentTypeLoader:
        calls:
            - [setParam, ["contentTypeIdentifier", "%ezplatform.user.content_type_identifier%"]]

    # Default implementations
    EzSystems\EzPlatformUser\ConfigResolver\RegistrationGroupLoader: '@EzSystems\EzPlatformUser\ConfigResolver\ConfigurableRegistrationGroupLoader'
    EzSystems\EzPlatformUser\ConfigResolver\RegistrationContentTypeLoader: '@EzSystems\EzPlatformUser\ConfigResolver\ConfigurableRegistrationContentTypeLoader'

    EzSystems\EzPlatformUser\Form\DataMapper\UserRegisterMapper:
        calls:
            - [setParam, ["language", "@=service('ezpublish.config.resolver').getParameter('languages', null, null)[0]"]]

    EzSystems\EzPlatformUser\Form\Processor\UserRegisterFormProcessor:
        tags:
            - { name: kernel.event_subscriber }

    EzSystems\EzPlatformUser\Templating\Twig\DateTimeExtension:
        arguments:
            $shortDateTimeFormatter: '@ezplatform.user.settings.short_datetime_format.formatter'
            $shortDateFormatter: '@ezplatform.user.settings.short_date_format.formatter'
            $shortTimeFormatter: '@ezplatform.user.settings.short_time_format.formatter'
            $fullDateTimeFormatter: '@ezplatform.user.settings.full_datetime_format.formatter'
            $fullDateFormatter: '@ezplatform.user.settings.full_date_format.formatter'
            $fullTimeFormatter: '@ezplatform.user.settings.full_time_format.formatter'
        tags:
            - { name: twig.extension }

    EzSystems\EzPlatformUser\ExceptionHandler\NullActionResultHandler: ~
    EzSystems\EzPlatformUser\ExceptionHandler\ActionResultHandler: '@EzSystems\EzPlatformUser\ExceptionHandler\ActionResultHandler'
