services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: false

    EzSystems\EzPlatformUser\UserSetting\:
        resource: "../../../lib/UserSetting/*"

    #
    # User Settings Implementations
    #
    EzSystems\EzPlatformUser\UserSetting\Setting\Timezone:
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: timezone }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: timezone }

    EzSystems\EzPlatformUser\UserSetting\Setting\SubitemsLimit:
        arguments:
            $subitemsLimit: '$subitems_module.limit$'
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: subitems_limit }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: subitems_limit }

    EzSystems\EzPlatformUser\UserSetting\Setting\CharacterCounter:
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: character_counter }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: character_counter }

    EzSystems\EzPlatformUser\UserSetting\Setting\FullDateTimeFormat:
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: full_datetime_format }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: full_datetime_format }

    EzSystems\EzPlatformUser\UserSetting\Setting\ShortDateTimeFormat:
        tags:
            - { name: ezplatform.admin_ui.user_setting.value, identifier: short_datetime_format }
            - { name: ezplatform.admin_ui.user_setting.form_mapper, identifier: short_datetime_format }
